let produtos = [
    {
        categoria: "Hardware",
        tipo: "Processador",
        nome: "Intel Core i7-10700K",
        marca: "Intel",
        preco: 350.00,
        vendas: 105,
        anuncios: 12 
    },
    {
        categoria: "Hardware",
        tipo: "Memória RAM",
        nome: "Corsair Vengeance LPX 16GB",
        marca: "Corsair",
        preco: 120.00,
        vendas: 20,
        anuncios: 12
    },
    {
        categoria: "Periféricos",
        tipo: "Mouse",
        nome: "Logitech G502",
        marca: "Logitech",
        preco: 60.00,
        vendas: 300,
        anuncios: 65,
    },
    {
        categoria: "Periféricos",
        tipo: "Monitor",
        nome: "Dell Ultrasharp U2719D",
        marca: "Dell",
        preco: 400.00,
        vendas: 87,
        anuncios: 41,
    },
    {
        categoria: "Hardware",
        tipo: "Placa de Vídeo",
        nome: "NVIDIA GeForce RTX 3080",
        marca: "NVIDIA",
        preco: 799.00,
        vendas: 40,
        anuncios: 25,
    },
    {
        categoria: "Periféricos",
        tipo: "Teclado",
        nome: "Razer BlackWidow Elite",
        marca: "Razer",
        preco: 150.00,
        vendas: 150,
        anuncios: 30,
    },
    {
        categoria: "Hardware",
        tipo: "SSD",
        nome: "Samsung 970 EVO 1TB",
        marca: "Samsung",
        preco: 200.00,
        vendas: 70,
        anuncios: 18,
    },
    {
        categoria: "Periféricos",
        tipo: "Headset",
        nome: "HyperX Cloud II",
        marca: "HyperX",
        preco: 100.00,
        vendas: 200,
        anuncios: 45,
    },
    {
        categoria: "Hardware",
        tipo: "Placa-mãe",
        nome: "ASUS ROG Strix Z590-E Gaming",
        marca: "ASUS",
        preco: 350.00,
        vendas: 30,
        anuncios: 10,
    },
    {
        categoria: "Periféricos",
        tipo: "Webcam",
        nome: "Logitech C920 HD Pro",
        marca: "Logitech",
        preco: 80.00,
        vendas: 100,
        anuncios: 20,
    },
];

module.exports = produtos;
